// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/service.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public interface CreateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instrument.v1.CreateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   * @return Whether the instrument field is set.
   */
  boolean hasInstrument();
  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   * @return The instrument.
   */
  com.grpcdemo.instrument.v1.proto.instrument.Instrument getInstrument();
  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder getInstrumentOrBuilder();
}
