// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/service.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public interface GetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instrument.v1.GetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();
}
