// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/service.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

/**
 * Protobuf type {@code instrument.v1.GetResponse}
 */
public final class GetResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instrument.v1.GetResponse)
    GetResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      GetResponse.class.getName());
  }
  // Use GetResponse.newBuilder() to construct.
  private GetResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GetResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcdemo.instrument.v1.proto.instrument.ServiceProto.internal_static_instrument_v1_GetResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcdemo.instrument.v1.proto.instrument.ServiceProto.internal_static_instrument_v1_GetResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcdemo.instrument.v1.proto.instrument.GetResponse.class, com.grpcdemo.instrument.v1.proto.instrument.GetResponse.Builder.class);
  }

  private int bitField0_;
  public static final int INSTRUMENT_FIELD_NUMBER = 1;
  private com.grpcdemo.instrument.v1.proto.instrument.Instrument instrument_;
  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   * @return Whether the instrument field is set.
   */
  @java.lang.Override
  public boolean hasInstrument() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   * @return The instrument.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.Instrument getInstrument() {
    return instrument_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance() : instrument_;
  }
  /**
   * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder getInstrumentOrBuilder() {
    return instrument_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance() : instrument_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getInstrument());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getInstrument());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcdemo.instrument.v1.proto.instrument.GetResponse)) {
      return super.equals(obj);
    }
    com.grpcdemo.instrument.v1.proto.instrument.GetResponse other = (com.grpcdemo.instrument.v1.proto.instrument.GetResponse) obj;

    if (hasInstrument() != other.hasInstrument()) return false;
    if (hasInstrument()) {
      if (!getInstrument()
          .equals(other.getInstrument())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasInstrument()) {
      hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
      hash = (53 * hash) + getInstrument().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcdemo.instrument.v1.proto.instrument.GetResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instrument.v1.GetResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instrument.v1.GetResponse)
      com.grpcdemo.instrument.v1.proto.instrument.GetResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcdemo.instrument.v1.proto.instrument.ServiceProto.internal_static_instrument_v1_GetResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcdemo.instrument.v1.proto.instrument.ServiceProto.internal_static_instrument_v1_GetResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcdemo.instrument.v1.proto.instrument.GetResponse.class, com.grpcdemo.instrument.v1.proto.instrument.GetResponse.Builder.class);
    }

    // Construct using com.grpcdemo.instrument.v1.proto.instrument.GetResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getInstrumentFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      instrument_ = null;
      if (instrumentBuilder_ != null) {
        instrumentBuilder_.dispose();
        instrumentBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.ServiceProto.internal_static_instrument_v1_GetResponse_descriptor;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.GetResponse getDefaultInstanceForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.GetResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.GetResponse build() {
      com.grpcdemo.instrument.v1.proto.instrument.GetResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.GetResponse buildPartial() {
      com.grpcdemo.instrument.v1.proto.instrument.GetResponse result = new com.grpcdemo.instrument.v1.proto.instrument.GetResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.grpcdemo.instrument.v1.proto.instrument.GetResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.instrument_ = instrumentBuilder_ == null
            ? instrument_
            : instrumentBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcdemo.instrument.v1.proto.instrument.GetResponse) {
        return mergeFrom((com.grpcdemo.instrument.v1.proto.instrument.GetResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcdemo.instrument.v1.proto.instrument.GetResponse other) {
      if (other == com.grpcdemo.instrument.v1.proto.instrument.GetResponse.getDefaultInstance()) return this;
      if (other.hasInstrument()) {
        mergeInstrument(other.getInstrument());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getInstrumentFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.grpcdemo.instrument.v1.proto.instrument.Instrument instrument_;
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.Instrument, com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder, com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder> instrumentBuilder_;
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     * @return Whether the instrument field is set.
     */
    public boolean hasInstrument() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     * @return The instrument.
     */
    public com.grpcdemo.instrument.v1.proto.instrument.Instrument getInstrument() {
      if (instrumentBuilder_ == null) {
        return instrument_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance() : instrument_;
      } else {
        return instrumentBuilder_.getMessage();
      }
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public Builder setInstrument(com.grpcdemo.instrument.v1.proto.instrument.Instrument value) {
      if (instrumentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        instrument_ = value;
      } else {
        instrumentBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public Builder setInstrument(
        com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder builderForValue) {
      if (instrumentBuilder_ == null) {
        instrument_ = builderForValue.build();
      } else {
        instrumentBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public Builder mergeInstrument(com.grpcdemo.instrument.v1.proto.instrument.Instrument value) {
      if (instrumentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          instrument_ != null &&
          instrument_ != com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance()) {
          getInstrumentBuilder().mergeFrom(value);
        } else {
          instrument_ = value;
        }
      } else {
        instrumentBuilder_.mergeFrom(value);
      }
      if (instrument_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public Builder clearInstrument() {
      bitField0_ = (bitField0_ & ~0x00000001);
      instrument_ = null;
      if (instrumentBuilder_ != null) {
        instrumentBuilder_.dispose();
        instrumentBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder getInstrumentBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getInstrumentFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder getInstrumentOrBuilder() {
      if (instrumentBuilder_ != null) {
        return instrumentBuilder_.getMessageOrBuilder();
      } else {
        return instrument_ == null ?
            com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance() : instrument_;
      }
    }
    /**
     * <code>.instrument.v1.Instrument instrument = 1 [json_name = "instrument"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.Instrument, com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder, com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder> 
        getInstrumentFieldBuilder() {
      if (instrumentBuilder_ == null) {
        instrumentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.Instrument, com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder, com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder>(
                getInstrument(),
                getParentForChildren(),
                isClean());
        instrument_ = null;
      }
      return instrumentBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:instrument.v1.GetResponse)
  }

  // @@protoc_insertion_point(class_scope:instrument.v1.GetResponse)
  private static final com.grpcdemo.instrument.v1.proto.instrument.GetResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcdemo.instrument.v1.proto.instrument.GetResponse();
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.GetResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetResponse>() {
    @java.lang.Override
    public GetResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.GetResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

