// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/instrument.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

/**
 * Protobuf type {@code instrument.v1.Instrument}
 */
public final class Instrument extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instrument.v1.Instrument)
    InstrumentOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      Instrument.class.getName());
  }
  // Use Instrument.newBuilder() to construct.
  private Instrument(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Instrument() {
    uid_ = "";
    name_ = "";
    symbol_ = "";
    logoUrl_ = "";
    labels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 11:
        return internalGetMetadata();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcdemo.instrument.v1.proto.instrument.Instrument.class, com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder.class);
  }

  private int pairCase_ = 0;
  @SuppressWarnings("serial")
  private java.lang.Object pair_;
  public enum PairCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    TRY_PAIR(6),
    USDT_PAIR(7),
    USD_PAIR(8),
    PAIR_NOT_SET(0);
    private final int value;
    private PairCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PairCase valueOf(int value) {
      return forNumber(value);
    }

    public static PairCase forNumber(int value) {
      switch (value) {
        case 6: return TRY_PAIR;
        case 7: return USDT_PAIR;
        case 8: return USD_PAIR;
        case 0: return PAIR_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public PairCase
  getPairCase() {
    return PairCase.forNumber(
        pairCase_);
  }

  public static final int UID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uid_ = "";
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 3 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 3 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOGO_URL_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object logoUrl_ = "";
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The logoUrl.
   */
  @java.lang.Override
  public java.lang.String getLogoUrl() {
    java.lang.Object ref = logoUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      logoUrl_ = s;
      return s;
    }
  }
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The bytes for logoUrl.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLogoUrlBytes() {
    java.lang.Object ref = logoUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      logoUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRY_PAIR_FIELD_NUMBER = 6;
  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   * @return Whether the tryPair field is set.
   */
  @java.lang.Override
  public boolean hasTryPair() {
    return pairCase_ == 6;
  }
  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   * @return The tryPair.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getTryPair() {
    if (pairCase_ == 6) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }
  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getTryPairOrBuilder() {
    if (pairCase_ == 6) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }

  public static final int USDT_PAIR_FIELD_NUMBER = 7;
  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   * @return Whether the usdtPair field is set.
   */
  @java.lang.Override
  public boolean hasUsdtPair() {
    return pairCase_ == 7;
  }
  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   * @return The usdtPair.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdtPair() {
    if (pairCase_ == 7) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }
  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdtPairOrBuilder() {
    if (pairCase_ == 7) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }

  public static final int USD_PAIR_FIELD_NUMBER = 8;
  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   * @return Whether the usdPair field is set.
   */
  @java.lang.Override
  public boolean hasUsdPair() {
    return pairCase_ == 8;
  }
  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   * @return The usdPair.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdPair() {
    if (pairCase_ == 8) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }
  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdPairOrBuilder() {
    if (pairCase_ == 8) {
       return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
    }
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
  }

  public static final int LABELS_FIELD_NUMBER = 9;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList labels_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @return A list containing the labels.
   */
  public com.google.protobuf.ProtocolStringList
      getLabelsList() {
    return labels_;
  }
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @return The count of labels.
   */
  public int getLabelsCount() {
    return labels_.size();
  }
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @param index The index of the element to return.
   * @return The labels at the given index.
   */
  public java.lang.String getLabels(int index) {
    return labels_.get(index);
  }
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the labels at the given index.
   */
  public com.google.protobuf.ByteString
      getLabelsBytes(int index) {
    return labels_.getByteString(index);
  }

  public static final int VERSION_FIELD_NUMBER = 10;
  private long version_ = 0L;
  /**
   * <code>int64 version = 10 [json_name = "version"];</code>
   * @return The version.
   */
  @java.lang.Override
  public long getVersion() {
    return version_;
  }

  public static final int METADATA_FIELD_NUMBER = 11;
  private static final class MetadataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_MetadataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> metadata_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetMetadata() {
    if (metadata_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          MetadataDefaultEntryHolder.defaultEntry);
    }
    return metadata_;
  }
  public int getMetadataCount() {
    return internalGetMetadata().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public boolean containsMetadata(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetMetadata().getMap().containsKey(key);
  }
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
    return getMetadataMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
    return internalGetMetadata().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  @java.lang.Override
  public java.lang.String getMetadataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetMetadata().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logoUrl_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, logoUrl_);
    }
    if (pairCase_ == 6) {
      output.writeMessage(6, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    if (pairCase_ == 7) {
      output.writeMessage(7, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    if (pairCase_ == 8) {
      output.writeMessage(8, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    for (int i = 0; i < labels_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 9, labels_.getRaw(i));
    }
    if (version_ != 0L) {
      output.writeInt64(10, version_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetMetadata(),
        MetadataDefaultEntryHolder.defaultEntry,
        11);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(logoUrl_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, logoUrl_);
    }
    if (pairCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    if (pairCase_ == 7) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    if (pairCase_ == 8) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < labels_.size(); i++) {
        dataSize += computeStringSizeNoTag(labels_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getLabelsList().size();
    }
    if (version_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, version_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetMetadata().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      metadata__ = MetadataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, metadata__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcdemo.instrument.v1.proto.instrument.Instrument)) {
      return super.equals(obj);
    }
    com.grpcdemo.instrument.v1.proto.instrument.Instrument other = (com.grpcdemo.instrument.v1.proto.instrument.Instrument) obj;

    if (!getUid()
        .equals(other.getUid())) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getLogoUrl()
        .equals(other.getLogoUrl())) return false;
    if (!getLabelsList()
        .equals(other.getLabelsList())) return false;
    if (getVersion()
        != other.getVersion()) return false;
    if (!internalGetMetadata().equals(
        other.internalGetMetadata())) return false;
    if (!getPairCase().equals(other.getPairCase())) return false;
    switch (pairCase_) {
      case 6:
        if (!getTryPair()
            .equals(other.getTryPair())) return false;
        break;
      case 7:
        if (!getUsdtPair()
            .equals(other.getUsdtPair())) return false;
        break;
      case 8:
        if (!getUsdPair()
            .equals(other.getUsdPair())) return false;
        break;
      case 0:
      default:
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + LOGO_URL_FIELD_NUMBER;
    hash = (53 * hash) + getLogoUrl().hashCode();
    if (getLabelsCount() > 0) {
      hash = (37 * hash) + LABELS_FIELD_NUMBER;
      hash = (53 * hash) + getLabelsList().hashCode();
    }
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getVersion());
    if (!internalGetMetadata().getMap().isEmpty()) {
      hash = (37 * hash) + METADATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetMetadata().hashCode();
    }
    switch (pairCase_) {
      case 6:
        hash = (37 * hash) + TRY_PAIR_FIELD_NUMBER;
        hash = (53 * hash) + getTryPair().hashCode();
        break;
      case 7:
        hash = (37 * hash) + USDT_PAIR_FIELD_NUMBER;
        hash = (53 * hash) + getUsdtPair().hashCode();
        break;
      case 8:
        hash = (37 * hash) + USD_PAIR_FIELD_NUMBER;
        hash = (53 * hash) + getUsdPair().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcdemo.instrument.v1.proto.instrument.Instrument prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instrument.v1.Instrument}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instrument.v1.Instrument)
      com.grpcdemo.instrument.v1.proto.instrument.InstrumentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 11:
          return internalGetMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 11:
          return internalGetMutableMetadata();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcdemo.instrument.v1.proto.instrument.Instrument.class, com.grpcdemo.instrument.v1.proto.instrument.Instrument.Builder.class);
    }

    // Construct using com.grpcdemo.instrument.v1.proto.instrument.Instrument.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = "";
      name_ = "";
      symbol_ = "";
      logoUrl_ = "";
      if (tryPairBuilder_ != null) {
        tryPairBuilder_.clear();
      }
      if (usdtPairBuilder_ != null) {
        usdtPairBuilder_.clear();
      }
      if (usdPairBuilder_ != null) {
        usdPairBuilder_.clear();
      }
      labels_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      version_ = 0L;
      internalGetMutableMetadata().clear();
      pairCase_ = 0;
      pair_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.InstrumentProto.internal_static_instrument_v1_Instrument_descriptor;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Instrument getDefaultInstanceForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Instrument build() {
      com.grpcdemo.instrument.v1.proto.instrument.Instrument result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Instrument buildPartial() {
      com.grpcdemo.instrument.v1.proto.instrument.Instrument result = new com.grpcdemo.instrument.v1.proto.instrument.Instrument(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      buildPartialOneofs(result);
      onBuilt();
      return result;
    }

    private void buildPartial0(com.grpcdemo.instrument.v1.proto.instrument.Instrument result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.logoUrl_ = logoUrl_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        labels_.makeImmutable();
        result.labels_ = labels_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.version_ = version_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.metadata_ = internalGetMetadata();
        result.metadata_.makeImmutable();
      }
    }

    private void buildPartialOneofs(com.grpcdemo.instrument.v1.proto.instrument.Instrument result) {
      result.pairCase_ = pairCase_;
      result.pair_ = this.pair_;
      if (pairCase_ == 6 &&
          tryPairBuilder_ != null) {
        result.pair_ = tryPairBuilder_.build();
      }
      if (pairCase_ == 7 &&
          usdtPairBuilder_ != null) {
        result.pair_ = usdtPairBuilder_.build();
      }
      if (pairCase_ == 8 &&
          usdPairBuilder_ != null) {
        result.pair_ = usdPairBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcdemo.instrument.v1.proto.instrument.Instrument) {
        return mergeFrom((com.grpcdemo.instrument.v1.proto.instrument.Instrument)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcdemo.instrument.v1.proto.instrument.Instrument other) {
      if (other == com.grpcdemo.instrument.v1.proto.instrument.Instrument.getDefaultInstance()) return this;
      if (!other.getUid().isEmpty()) {
        uid_ = other.uid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getLogoUrl().isEmpty()) {
        logoUrl_ = other.logoUrl_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.labels_.isEmpty()) {
        if (labels_.isEmpty()) {
          labels_ = other.labels_;
          bitField0_ |= 0x00000080;
        } else {
          ensureLabelsIsMutable();
          labels_.addAll(other.labels_);
        }
        onChanged();
      }
      if (other.getVersion() != 0L) {
        setVersion(other.getVersion());
      }
      internalGetMutableMetadata().mergeFrom(
          other.internalGetMetadata());
      bitField0_ |= 0x00000200;
      switch (other.getPairCase()) {
        case TRY_PAIR: {
          mergeTryPair(other.getTryPair());
          break;
        }
        case USDT_PAIR: {
          mergeUsdtPair(other.getUsdtPair());
          break;
        }
        case USD_PAIR: {
          mergeUsdPair(other.getUsdPair());
          break;
        }
        case PAIR_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              logoUrl_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 50: {
              input.readMessage(
                  getTryPairFieldBuilder().getBuilder(),
                  extensionRegistry);
              pairCase_ = 6;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getUsdtPairFieldBuilder().getBuilder(),
                  extensionRegistry);
              pairCase_ = 7;
              break;
            } // case 58
            case 66: {
              input.readMessage(
                  getUsdPairFieldBuilder().getBuilder(),
                  extensionRegistry);
              pairCase_ = 8;
              break;
            } // case 66
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();
              ensureLabelsIsMutable();
              labels_.add(s);
              break;
            } // case 74
            case 80: {
              version_ = input.readInt64();
              bitField0_ |= 0x00000100;
              break;
            } // case 80
            case 90: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              metadata__ = input.readMessage(
                  MetadataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableMetadata().getMutableMap().put(
                  metadata__.getKey(), metadata__.getValue());
              bitField0_ |= 0x00000200;
              break;
            } // case 90
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int pairCase_ = 0;
    private java.lang.Object pair_;
    public PairCase
        getPairCase() {
      return PairCase.forNumber(
          pairCase_);
    }

    public Builder clearPair() {
      pairCase_ = 0;
      pair_ = null;
      onChanged();
      return this;
    }

    private int bitField0_;

    private java.lang.Object uid_ = "";
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      uid_ = getDefaultInstance().getUid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 3 [json_name = "symbol"];</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 3 [json_name = "symbol"];</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 3 [json_name = "symbol"];</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 3 [json_name = "symbol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 3 [json_name = "symbol"];</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object logoUrl_ = "";
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return The logoUrl.
     */
    public java.lang.String getLogoUrl() {
      java.lang.Object ref = logoUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        logoUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return The bytes for logoUrl.
     */
    public com.google.protobuf.ByteString
        getLogoUrlBytes() {
      java.lang.Object ref = logoUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        logoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @param value The logoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLogoUrl(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      logoUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLogoUrl() {
      logoUrl_ = getDefaultInstance().getLogoUrl();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
     * @param value The bytes for logoUrl to set.
     * @return This builder for chaining.
     */
    public Builder setLogoUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      logoUrl_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> tryPairBuilder_;
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     * @return Whether the tryPair field is set.
     */
    @java.lang.Override
    public boolean hasTryPair() {
      return pairCase_ == 6;
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     * @return The tryPair.
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getTryPair() {
      if (tryPairBuilder_ == null) {
        if (pairCase_ == 6) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      } else {
        if (pairCase_ == 6) {
          return tryPairBuilder_.getMessage();
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    public Builder setTryPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (tryPairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pair_ = value;
        onChanged();
      } else {
        tryPairBuilder_.setMessage(value);
      }
      pairCase_ = 6;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    public Builder setTryPair(
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder builderForValue) {
      if (tryPairBuilder_ == null) {
        pair_ = builderForValue.build();
        onChanged();
      } else {
        tryPairBuilder_.setMessage(builderForValue.build());
      }
      pairCase_ = 6;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    public Builder mergeTryPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (tryPairBuilder_ == null) {
        if (pairCase_ == 6 &&
            pair_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance()) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.newBuilder((com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_)
              .mergeFrom(value).buildPartial();
        } else {
          pair_ = value;
        }
        onChanged();
      } else {
        if (pairCase_ == 6) {
          tryPairBuilder_.mergeFrom(value);
        } else {
          tryPairBuilder_.setMessage(value);
        }
      }
      pairCase_ = 6;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    public Builder clearTryPair() {
      if (tryPairBuilder_ == null) {
        if (pairCase_ == 6) {
          pairCase_ = 0;
          pair_ = null;
          onChanged();
        }
      } else {
        if (pairCase_ == 6) {
          pairCase_ = 0;
          pair_ = null;
        }
        tryPairBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder getTryPairBuilder() {
      return getTryPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getTryPairOrBuilder() {
      if ((pairCase_ == 6) && (tryPairBuilder_ != null)) {
        return tryPairBuilder_.getMessageOrBuilder();
      } else {
        if (pairCase_ == 6) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> 
        getTryPairFieldBuilder() {
      if (tryPairBuilder_ == null) {
        if (!(pairCase_ == 6)) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
        }
        tryPairBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder>(
                (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_,
                getParentForChildren(),
                isClean());
        pair_ = null;
      }
      pairCase_ = 6;
      onChanged();
      return tryPairBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> usdtPairBuilder_;
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     * @return Whether the usdtPair field is set.
     */
    @java.lang.Override
    public boolean hasUsdtPair() {
      return pairCase_ == 7;
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     * @return The usdtPair.
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdtPair() {
      if (usdtPairBuilder_ == null) {
        if (pairCase_ == 7) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      } else {
        if (pairCase_ == 7) {
          return usdtPairBuilder_.getMessage();
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    public Builder setUsdtPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (usdtPairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pair_ = value;
        onChanged();
      } else {
        usdtPairBuilder_.setMessage(value);
      }
      pairCase_ = 7;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    public Builder setUsdtPair(
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder builderForValue) {
      if (usdtPairBuilder_ == null) {
        pair_ = builderForValue.build();
        onChanged();
      } else {
        usdtPairBuilder_.setMessage(builderForValue.build());
      }
      pairCase_ = 7;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    public Builder mergeUsdtPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (usdtPairBuilder_ == null) {
        if (pairCase_ == 7 &&
            pair_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance()) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.newBuilder((com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_)
              .mergeFrom(value).buildPartial();
        } else {
          pair_ = value;
        }
        onChanged();
      } else {
        if (pairCase_ == 7) {
          usdtPairBuilder_.mergeFrom(value);
        } else {
          usdtPairBuilder_.setMessage(value);
        }
      }
      pairCase_ = 7;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    public Builder clearUsdtPair() {
      if (usdtPairBuilder_ == null) {
        if (pairCase_ == 7) {
          pairCase_ = 0;
          pair_ = null;
          onChanged();
        }
      } else {
        if (pairCase_ == 7) {
          pairCase_ = 0;
          pair_ = null;
        }
        usdtPairBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder getUsdtPairBuilder() {
      return getUsdtPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdtPairOrBuilder() {
      if ((pairCase_ == 7) && (usdtPairBuilder_ != null)) {
        return usdtPairBuilder_.getMessageOrBuilder();
      } else {
        if (pairCase_ == 7) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> 
        getUsdtPairFieldBuilder() {
      if (usdtPairBuilder_ == null) {
        if (!(pairCase_ == 7)) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
        }
        usdtPairBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder>(
                (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_,
                getParentForChildren(),
                isClean());
        pair_ = null;
      }
      pairCase_ = 7;
      onChanged();
      return usdtPairBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> usdPairBuilder_;
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     * @return Whether the usdPair field is set.
     */
    @java.lang.Override
    public boolean hasUsdPair() {
      return pairCase_ == 8;
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     * @return The usdPair.
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdPair() {
      if (usdPairBuilder_ == null) {
        if (pairCase_ == 8) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      } else {
        if (pairCase_ == 8) {
          return usdPairBuilder_.getMessage();
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    public Builder setUsdPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (usdPairBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pair_ = value;
        onChanged();
      } else {
        usdPairBuilder_.setMessage(value);
      }
      pairCase_ = 8;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    public Builder setUsdPair(
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder builderForValue) {
      if (usdPairBuilder_ == null) {
        pair_ = builderForValue.build();
        onChanged();
      } else {
        usdPairBuilder_.setMessage(builderForValue.build());
      }
      pairCase_ = 8;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    public Builder mergeUsdPair(com.grpcdemo.instrument.v1.proto.instrument.TradingPair value) {
      if (usdPairBuilder_ == null) {
        if (pairCase_ == 8 &&
            pair_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance()) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.newBuilder((com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_)
              .mergeFrom(value).buildPartial();
        } else {
          pair_ = value;
        }
        onChanged();
      } else {
        if (pairCase_ == 8) {
          usdPairBuilder_.mergeFrom(value);
        } else {
          usdPairBuilder_.setMessage(value);
        }
      }
      pairCase_ = 8;
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    public Builder clearUsdPair() {
      if (usdPairBuilder_ == null) {
        if (pairCase_ == 8) {
          pairCase_ = 0;
          pair_ = null;
          onChanged();
        }
      } else {
        if (pairCase_ == 8) {
          pairCase_ = 0;
          pair_ = null;
        }
        usdPairBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder getUsdPairBuilder() {
      return getUsdPairFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdPairOrBuilder() {
      if ((pairCase_ == 8) && (usdPairBuilder_ != null)) {
        return usdPairBuilder_.getMessageOrBuilder();
      } else {
        if (pairCase_ == 8) {
          return (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_;
        }
        return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
      }
    }
    /**
     * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder> 
        getUsdPairFieldBuilder() {
      if (usdPairBuilder_ == null) {
        if (!(pairCase_ == 8)) {
          pair_ = com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
        }
        usdPairBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.TradingPair, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder>(
                (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) pair_,
                getParentForChildren(),
                isClean());
        pair_ = null;
      }
      pairCase_ = 8;
      onChanged();
      return usdPairBuilder_;
    }

    private com.google.protobuf.LazyStringArrayList labels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureLabelsIsMutable() {
      if (!labels_.isModifiable()) {
        labels_ = new com.google.protobuf.LazyStringArrayList(labels_);
      }
      bitField0_ |= 0x00000080;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @return A list containing the labels.
     */
    public com.google.protobuf.ProtocolStringList
        getLabelsList() {
      labels_.makeImmutable();
      return labels_;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @return The count of labels.
     */
    public int getLabelsCount() {
      return labels_.size();
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param index The index of the element to return.
     * @return The labels at the given index.
     */
    public java.lang.String getLabels(int index) {
      return labels_.get(index);
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param index The index of the value to return.
     * @return The bytes of the labels at the given index.
     */
    public com.google.protobuf.ByteString
        getLabelsBytes(int index) {
      return labels_.getByteString(index);
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param index The index to set the value at.
     * @param value The labels to set.
     * @return This builder for chaining.
     */
    public Builder setLabels(
        int index, java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLabelsIsMutable();
      labels_.set(index, value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param value The labels to add.
     * @return This builder for chaining.
     */
    public Builder addLabels(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      ensureLabelsIsMutable();
      labels_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param values The labels to add.
     * @return This builder for chaining.
     */
    public Builder addAllLabels(
        java.lang.Iterable<java.lang.String> values) {
      ensureLabelsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, labels_);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @return This builder for chaining.
     */
    public Builder clearLabels() {
      labels_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000080);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string labels = 9 [json_name = "labels"];</code>
     * @param value The bytes of the labels to add.
     * @return This builder for chaining.
     */
    public Builder addLabelsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      ensureLabelsIsMutable();
      labels_.add(value);
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }

    private long version_ ;
    /**
     * <code>int64 version = 10 [json_name = "version"];</code>
     * @return The version.
     */
    @java.lang.Override
    public long getVersion() {
      return version_;
    }
    /**
     * <code>int64 version = 10 [json_name = "version"];</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(long value) {

      version_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int64 version = 10 [json_name = "version"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000100);
      version_ = 0L;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> metadata_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMetadata() {
      if (metadata_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      return metadata_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableMetadata() {
      if (metadata_ == null) {
        metadata_ = com.google.protobuf.MapField.newMapField(
            MetadataDefaultEntryHolder.defaultEntry);
      }
      if (!metadata_.isMutable()) {
        metadata_ = metadata_.copy();
      }
      bitField0_ |= 0x00000200;
      onChanged();
      return metadata_;
    }
    public int getMetadataCount() {
      return internalGetMetadata().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public boolean containsMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetMetadata().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMetadataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getMetadata() {
      return getMetadataMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getMetadataMap() {
      return internalGetMetadata().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getMetadataOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    @java.lang.Override
    public java.lang.String getMetadataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetMetadata().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearMetadata() {
      bitField0_ = (bitField0_ & ~0x00000200);
      internalGetMutableMetadata().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    public Builder removeMetadata(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableMetadata().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableMetadata() {
      bitField0_ |= 0x00000200;
      return internalGetMutableMetadata().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    public Builder putMetadata(
        java.lang.String key,
        java.lang.String value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableMetadata().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000200;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
     */
    public Builder putAllMetadata(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableMetadata().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000200;
      return this;
    }

    // @@protoc_insertion_point(builder_scope:instrument.v1.Instrument)
  }

  // @@protoc_insertion_point(class_scope:instrument.v1.Instrument)
  private static final com.grpcdemo.instrument.v1.proto.instrument.Instrument DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcdemo.instrument.v1.proto.instrument.Instrument();
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Instrument getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Instrument>
      PARSER = new com.google.protobuf.AbstractParser<Instrument>() {
    @java.lang.Override
    public Instrument parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Instrument> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Instrument> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.Instrument getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

