// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/instrument.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public interface InstrumentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instrument.v1.Instrument)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string symbol = 3 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 3 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The logoUrl.
   */
  java.lang.String getLogoUrl();
  /**
   * <code>string logo_url = 4 [json_name = "logoUrl"];</code>
   * @return The bytes for logoUrl.
   */
  com.google.protobuf.ByteString
      getLogoUrlBytes();

  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   * @return Whether the tryPair field is set.
   */
  boolean hasTryPair();
  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   * @return The tryPair.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPair getTryPair();
  /**
   * <code>.instrument.v1.TradingPair try_pair = 6 [json_name = "tryPair"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getTryPairOrBuilder();

  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   * @return Whether the usdtPair field is set.
   */
  boolean hasUsdtPair();
  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   * @return The usdtPair.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdtPair();
  /**
   * <code>.instrument.v1.TradingPair usdt_pair = 7 [json_name = "usdtPair"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdtPairOrBuilder();

  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   * @return Whether the usdPair field is set.
   */
  boolean hasUsdPair();
  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   * @return The usdPair.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPair getUsdPair();
  /**
   * <code>.instrument.v1.TradingPair usd_pair = 8 [json_name = "usdPair"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder getUsdPairOrBuilder();

  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @return A list containing the labels.
   */
  java.util.List<java.lang.String>
      getLabelsList();
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @return The count of labels.
   */
  int getLabelsCount();
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @param index The index of the element to return.
   * @return The labels at the given index.
   */
  java.lang.String getLabels(int index);
  /**
   * <code>repeated string labels = 9 [json_name = "labels"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the labels at the given index.
   */
  com.google.protobuf.ByteString
      getLabelsBytes(int index);

  /**
   * <code>int64 version = 10 [json_name = "version"];</code>
   * @return The version.
   */
  long getVersion();

  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  int getMetadataCount();
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  boolean containsMetadata(
      java.lang.String key);
  /**
   * Use {@link #getMetadataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getMetadata();
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getMetadataMap();
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  /* nullable */
java.lang.String getMetadataOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; metadata = 11 [json_name = "metadata"];</code>
   */
  java.lang.String getMetadataOrThrow(
      java.lang.String key);

  com.grpcdemo.instrument.v1.proto.instrument.Instrument.PairCase getPairCase();
}
