// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/threshold.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

/**
 * Protobuf type {@code instrument.v1.Threshold}
 */
public final class Threshold extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instrument.v1.Threshold)
    ThresholdOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      Threshold.class.getName());
  }
  // Use Threshold.newBuilder() to construct.
  private Threshold(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Threshold() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.internal_static_instrument_v1_Threshold_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.internal_static_instrument_v1_Threshold_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcdemo.instrument.v1.proto.instrument.Threshold.class, com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder.class);
  }

  public static final int MIN_AMOUNT_FIELD_NUMBER = 1;
  private double minAmount_ = 0D;
  /**
   * <code>double min_amount = 1 [json_name = "minAmount"];</code>
   * @return The minAmount.
   */
  @java.lang.Override
  public double getMinAmount() {
    return minAmount_;
  }

  public static final int MAX_AMOUNT_FIELD_NUMBER = 2;
  private double maxAmount_ = 0D;
  /**
   * <code>double max_amount = 2 [json_name = "maxAmount"];</code>
   * @return The maxAmount.
   */
  @java.lang.Override
  public double getMaxAmount() {
    return maxAmount_;
  }

  public static final int MIN_QUANTITY_FIELD_NUMBER = 3;
  private double minQuantity_ = 0D;
  /**
   * <code>double min_quantity = 3 [json_name = "minQuantity"];</code>
   * @return The minQuantity.
   */
  @java.lang.Override
  public double getMinQuantity() {
    return minQuantity_;
  }

  public static final int MAX_QUANTITY_FIELD_NUMBER = 4;
  private double maxQuantity_ = 0D;
  /**
   * <code>double max_quantity = 4 [json_name = "maxQuantity"];</code>
   * @return The maxQuantity.
   */
  @java.lang.Override
  public double getMaxQuantity() {
    return maxQuantity_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (java.lang.Double.doubleToRawLongBits(minAmount_) != 0) {
      output.writeDouble(1, minAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxAmount_) != 0) {
      output.writeDouble(2, maxAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(minQuantity_) != 0) {
      output.writeDouble(3, minQuantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxQuantity_) != 0) {
      output.writeDouble(4, maxQuantity_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (java.lang.Double.doubleToRawLongBits(minAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(1, minAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxAmount_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, maxAmount_);
    }
    if (java.lang.Double.doubleToRawLongBits(minQuantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, minQuantity_);
    }
    if (java.lang.Double.doubleToRawLongBits(maxQuantity_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(4, maxQuantity_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcdemo.instrument.v1.proto.instrument.Threshold)) {
      return super.equals(obj);
    }
    com.grpcdemo.instrument.v1.proto.instrument.Threshold other = (com.grpcdemo.instrument.v1.proto.instrument.Threshold) obj;

    if (java.lang.Double.doubleToLongBits(getMinAmount())
        != java.lang.Double.doubleToLongBits(
            other.getMinAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxAmount())
        != java.lang.Double.doubleToLongBits(
            other.getMaxAmount())) return false;
    if (java.lang.Double.doubleToLongBits(getMinQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getMinQuantity())) return false;
    if (java.lang.Double.doubleToLongBits(getMaxQuantity())
        != java.lang.Double.doubleToLongBits(
            other.getMaxQuantity())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMinAmount()));
    hash = (37 * hash) + MAX_AMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxAmount()));
    hash = (37 * hash) + MIN_QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMinQuantity()));
    hash = (37 * hash) + MAX_QUANTITY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMaxQuantity()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcdemo.instrument.v1.proto.instrument.Threshold prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instrument.v1.Threshold}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instrument.v1.Threshold)
      com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.internal_static_instrument_v1_Threshold_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.internal_static_instrument_v1_Threshold_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcdemo.instrument.v1.proto.instrument.Threshold.class, com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder.class);
    }

    // Construct using com.grpcdemo.instrument.v1.proto.instrument.Threshold.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      minAmount_ = 0D;
      maxAmount_ = 0D;
      minQuantity_ = 0D;
      maxQuantity_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.internal_static_instrument_v1_Threshold_descriptor;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Threshold getDefaultInstanceForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Threshold build() {
      com.grpcdemo.instrument.v1.proto.instrument.Threshold result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.Threshold buildPartial() {
      com.grpcdemo.instrument.v1.proto.instrument.Threshold result = new com.grpcdemo.instrument.v1.proto.instrument.Threshold(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.grpcdemo.instrument.v1.proto.instrument.Threshold result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.minAmount_ = minAmount_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.maxAmount_ = maxAmount_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minQuantity_ = minQuantity_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxQuantity_ = maxQuantity_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcdemo.instrument.v1.proto.instrument.Threshold) {
        return mergeFrom((com.grpcdemo.instrument.v1.proto.instrument.Threshold)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcdemo.instrument.v1.proto.instrument.Threshold other) {
      if (other == com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance()) return this;
      if (other.getMinAmount() != 0D) {
        setMinAmount(other.getMinAmount());
      }
      if (other.getMaxAmount() != 0D) {
        setMaxAmount(other.getMaxAmount());
      }
      if (other.getMinQuantity() != 0D) {
        setMinQuantity(other.getMinQuantity());
      }
      if (other.getMaxQuantity() != 0D) {
        setMaxQuantity(other.getMaxQuantity());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              minAmount_ = input.readDouble();
              bitField0_ |= 0x00000001;
              break;
            } // case 9
            case 17: {
              maxAmount_ = input.readDouble();
              bitField0_ |= 0x00000002;
              break;
            } // case 17
            case 25: {
              minQuantity_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            case 33: {
              maxQuantity_ = input.readDouble();
              bitField0_ |= 0x00000008;
              break;
            } // case 33
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private double minAmount_ ;
    /**
     * <code>double min_amount = 1 [json_name = "minAmount"];</code>
     * @return The minAmount.
     */
    @java.lang.Override
    public double getMinAmount() {
      return minAmount_;
    }
    /**
     * <code>double min_amount = 1 [json_name = "minAmount"];</code>
     * @param value The minAmount to set.
     * @return This builder for chaining.
     */
    public Builder setMinAmount(double value) {

      minAmount_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>double min_amount = 1 [json_name = "minAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMinAmount() {
      bitField0_ = (bitField0_ & ~0x00000001);
      minAmount_ = 0D;
      onChanged();
      return this;
    }

    private double maxAmount_ ;
    /**
     * <code>double max_amount = 2 [json_name = "maxAmount"];</code>
     * @return The maxAmount.
     */
    @java.lang.Override
    public double getMaxAmount() {
      return maxAmount_;
    }
    /**
     * <code>double max_amount = 2 [json_name = "maxAmount"];</code>
     * @param value The maxAmount to set.
     * @return This builder for chaining.
     */
    public Builder setMaxAmount(double value) {

      maxAmount_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>double max_amount = 2 [json_name = "maxAmount"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxAmount() {
      bitField0_ = (bitField0_ & ~0x00000002);
      maxAmount_ = 0D;
      onChanged();
      return this;
    }

    private double minQuantity_ ;
    /**
     * <code>double min_quantity = 3 [json_name = "minQuantity"];</code>
     * @return The minQuantity.
     */
    @java.lang.Override
    public double getMinQuantity() {
      return minQuantity_;
    }
    /**
     * <code>double min_quantity = 3 [json_name = "minQuantity"];</code>
     * @param value The minQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setMinQuantity(double value) {

      minQuantity_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double min_quantity = 3 [json_name = "minQuantity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMinQuantity() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minQuantity_ = 0D;
      onChanged();
      return this;
    }

    private double maxQuantity_ ;
    /**
     * <code>double max_quantity = 4 [json_name = "maxQuantity"];</code>
     * @return The maxQuantity.
     */
    @java.lang.Override
    public double getMaxQuantity() {
      return maxQuantity_;
    }
    /**
     * <code>double max_quantity = 4 [json_name = "maxQuantity"];</code>
     * @param value The maxQuantity to set.
     * @return This builder for chaining.
     */
    public Builder setMaxQuantity(double value) {

      maxQuantity_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>double max_quantity = 4 [json_name = "maxQuantity"];</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxQuantity() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxQuantity_ = 0D;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:instrument.v1.Threshold)
  }

  // @@protoc_insertion_point(class_scope:instrument.v1.Threshold)
  private static final com.grpcdemo.instrument.v1.proto.instrument.Threshold DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcdemo.instrument.v1.proto.instrument.Threshold();
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.Threshold getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Threshold>
      PARSER = new com.google.protobuf.AbstractParser<Threshold>() {
    @java.lang.Override
    public Threshold parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Threshold> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Threshold> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.Threshold getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

