// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/threshold.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public final class ThresholdProto {
  private ThresholdProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      ThresholdProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instrument_v1_Threshold_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instrument_v1_Threshold_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035instrument/v1/threshold.proto\022\rinstrum" +
      "ent.v1\"\217\001\n\tThreshold\022\035\n\nmin_amount\030\001 \001(\001" +
      "R\tminAmount\022\035\n\nmax_amount\030\002 \001(\001R\tmaxAmou" +
      "nt\022!\n\014min_quantity\030\003 \001(\001R\013minQuantity\022!\n" +
      "\014max_quantity\030\004 \001(\001R\013maxQuantityB\256\001\n+com" +
      ".grpcdemo.instrument.v1.proto.instrument" +
      "B\016ThresholdProtoP\001Z\032instrument/v1;instru" +
      "mentv1\242\002\003IXX\252\002\rInstrument.V1\312\002\rInstrumen" +
      "t\\V1\342\002\031Instrument\\V1\\GPBMetadata\352\002\016Instr" +
      "ument::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_instrument_v1_Threshold_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_instrument_v1_Threshold_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instrument_v1_Threshold_descriptor,
        new java.lang.String[] { "MinAmount", "MaxAmount", "MinQuantity", "MaxQuantity", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
