// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/trading_pair.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public final class TradingPairProto {
  private TradingPairProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      TradingPairProto.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instrument_v1_TradingPairItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instrument_v1_TradingPairItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_instrument_v1_TradingPair_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_instrument_v1_TradingPair_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n instrument/v1/trading_pair.proto\022\rinst" +
      "rument.v1\032\035instrument/v1/threshold.proto" +
      "\"b\n\017TradingPairItem\022\020\n\003uid\030\001 \001(\tR\003uid\022\026\n" +
      "\006symbol\030\002 \001(\tR\006symbol\022%\n\016decimal_places\030" +
      "\003 \001(\tR\rdecimalPlaces\"\261\002\n\013TradingPair\022\020\n\003" +
      "uid\030\001 \001(\tR\003uid\022\030\n\007buyable\030\002 \001(\010R\007buyable" +
      "\022\032\n\010sellable\030\003 \001(\010R\010sellable\0228\n\006status\030\004" +
      " \001(\0162 .instrument.v1.TradingPairStatusR\006" +
      "status\0222\n\004left\030\005 \001(\0132\036.instrument.v1.Tra" +
      "dingPairItemR\004left\0224\n\005right\030\006 \001(\0132\036.inst" +
      "rument.v1.TradingPairItemR\005right\0226\n\tthre" +
      "shold\030\007 \001(\0132\030.instrument.v1.ThresholdR\tt" +
      "hreshold*G\n\021TradingPairStatus\022\017\n\013UNSPECI" +
      "FIED\020\000\022\n\n\006ACTIVE\020\001\022\013\n\007PASSIVE\020\002\"\010\010\003\020\377\377\377\377" +
      "\007B\260\001\n+com.grpcdemo.instrument.v1.proto.i" +
      "nstrumentB\020TradingPairProtoP\001Z\032instrumen" +
      "t/v1;instrumentv1\242\002\003IXX\252\002\rInstrument.V1\312" +
      "\002\rInstrument\\V1\342\002\031Instrument\\V1\\GPBMetad" +
      "ata\352\002\016Instrument::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.getDescriptor(),
        });
    internal_static_instrument_v1_TradingPairItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_instrument_v1_TradingPairItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instrument_v1_TradingPairItem_descriptor,
        new java.lang.String[] { "Uid", "Symbol", "DecimalPlaces", });
    internal_static_instrument_v1_TradingPair_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_instrument_v1_TradingPair_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_instrument_v1_TradingPair_descriptor,
        new java.lang.String[] { "Uid", "Buyable", "Sellable", "Status", "Left", "Right", "Threshold", });
    descriptor.resolveAllFeaturesImmutable();
    com.grpcdemo.instrument.v1.proto.instrument.ThresholdProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
