// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/trading_pair.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

/**
 * Protobuf type {@code instrument.v1.TradingPairItem}
 */
public final class TradingPairItem extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instrument.v1.TradingPairItem)
    TradingPairItemOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      TradingPairItem.class.getName());
  }
  // Use TradingPairItem.newBuilder() to construct.
  private TradingPairItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TradingPairItem() {
    uid_ = "";
    symbol_ = "";
    decimalPlaces_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPairItem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPairItem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.class, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder.class);
  }

  public static final int UID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uid_ = "";
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SYMBOL_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object symbol_ = "";
  /**
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  @java.lang.Override
  public java.lang.String getSymbol() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      symbol_ = s;
      return s;
    }
  }
  /**
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSymbolBytes() {
    java.lang.Object ref = symbol_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      symbol_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DECIMAL_PLACES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object decimalPlaces_ = "";
  /**
   * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
   * @return The decimalPlaces.
   */
  @java.lang.Override
  public java.lang.String getDecimalPlaces() {
    java.lang.Object ref = decimalPlaces_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      decimalPlaces_ = s;
      return s;
    }
  }
  /**
   * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
   * @return The bytes for decimalPlaces.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDecimalPlacesBytes() {
    java.lang.Object ref = decimalPlaces_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      decimalPlaces_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(decimalPlaces_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, decimalPlaces_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(symbol_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, symbol_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(decimalPlaces_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, decimalPlaces_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem)) {
      return super.equals(obj);
    }
    com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem other = (com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem) obj;

    if (!getUid()
        .equals(other.getUid())) return false;
    if (!getSymbol()
        .equals(other.getSymbol())) return false;
    if (!getDecimalPlaces()
        .equals(other.getDecimalPlaces())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid().hashCode();
    hash = (37 * hash) + SYMBOL_FIELD_NUMBER;
    hash = (53 * hash) + getSymbol().hashCode();
    hash = (37 * hash) + DECIMAL_PLACES_FIELD_NUMBER;
    hash = (53 * hash) + getDecimalPlaces().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instrument.v1.TradingPairItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instrument.v1.TradingPairItem)
      com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPairItem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPairItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.class, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder.class);
    }

    // Construct using com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = "";
      symbol_ = "";
      decimalPlaces_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPairItem_descriptor;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getDefaultInstanceForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem build() {
      com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem buildPartial() {
      com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem result = new com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.symbol_ = symbol_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.decimalPlaces_ = decimalPlaces_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem) {
        return mergeFrom((com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem other) {
      if (other == com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance()) return this;
      if (!other.getUid().isEmpty()) {
        uid_ = other.uid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getSymbol().isEmpty()) {
        symbol_ = other.symbol_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDecimalPlaces().isEmpty()) {
        decimalPlaces_ = other.decimalPlaces_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              symbol_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              decimalPlaces_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object uid_ = "";
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      uid_ = getDefaultInstance().getUid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object symbol_ = "";
    /**
     * <code>string symbol = 2 [json_name = "symbol"];</code>
     * @return The symbol.
     */
    public java.lang.String getSymbol() {
      java.lang.Object ref = symbol_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        symbol_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string symbol = 2 [json_name = "symbol"];</code>
     * @return The bytes for symbol.
     */
    public com.google.protobuf.ByteString
        getSymbolBytes() {
      java.lang.Object ref = symbol_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        symbol_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string symbol = 2 [json_name = "symbol"];</code>
     * @param value The symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbol(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2 [json_name = "symbol"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSymbol() {
      symbol_ = getDefaultInstance().getSymbol();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string symbol = 2 [json_name = "symbol"];</code>
     * @param value The bytes for symbol to set.
     * @return This builder for chaining.
     */
    public Builder setSymbolBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      symbol_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object decimalPlaces_ = "";
    /**
     * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
     * @return The decimalPlaces.
     */
    public java.lang.String getDecimalPlaces() {
      java.lang.Object ref = decimalPlaces_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        decimalPlaces_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
     * @return The bytes for decimalPlaces.
     */
    public com.google.protobuf.ByteString
        getDecimalPlacesBytes() {
      java.lang.Object ref = decimalPlaces_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        decimalPlaces_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
     * @param value The decimalPlaces to set.
     * @return This builder for chaining.
     */
    public Builder setDecimalPlaces(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      decimalPlaces_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDecimalPlaces() {
      decimalPlaces_ = getDefaultInstance().getDecimalPlaces();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
     * @param value The bytes for decimalPlaces to set.
     * @return This builder for chaining.
     */
    public Builder setDecimalPlacesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      decimalPlaces_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:instrument.v1.TradingPairItem)
  }

  // @@protoc_insertion_point(class_scope:instrument.v1.TradingPairItem)
  private static final com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem();
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradingPairItem>
      PARSER = new com.google.protobuf.AbstractParser<TradingPairItem>() {
    @java.lang.Override
    public TradingPairItem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradingPairItem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradingPairItem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

