// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/trading_pair.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

/**
 * Protobuf type {@code instrument.v1.TradingPair}
 */
public final class TradingPair extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:instrument.v1.TradingPair)
    TradingPairOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 0,
      /* suffix= */ "",
      TradingPair.class.getName());
  }
  // Use TradingPair.newBuilder() to construct.
  private TradingPair(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private TradingPair() {
    uid_ = "";
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPair_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPair_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.grpcdemo.instrument.v1.proto.instrument.TradingPair.class, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder.class);
  }

  private int bitField0_;
  public static final int UID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object uid_ = "";
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  @java.lang.Override
  public java.lang.String getUid() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      uid_ = s;
      return s;
    }
  }
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getUidBytes() {
    java.lang.Object ref = uid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      uid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUYABLE_FIELD_NUMBER = 2;
  private boolean buyable_ = false;
  /**
   * <code>bool buyable = 2 [json_name = "buyable"];</code>
   * @return The buyable.
   */
  @java.lang.Override
  public boolean getBuyable() {
    return buyable_;
  }

  public static final int SELLABLE_FIELD_NUMBER = 3;
  private boolean sellable_ = false;
  /**
   * <code>bool sellable = 3 [json_name = "sellable"];</code>
   * @return The sellable.
   */
  @java.lang.Override
  public boolean getSellable() {
    return sellable_;
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_ = 0;
  /**
   * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus getStatus() {
    com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus result = com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.forNumber(status_);
    return result == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.UNRECOGNIZED : result;
  }

  public static final int LEFT_FIELD_NUMBER = 5;
  private com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem left_;
  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   * @return Whether the left field is set.
   */
  @java.lang.Override
  public boolean hasLeft() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   * @return The left.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getLeft() {
    return left_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : left_;
  }
  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getLeftOrBuilder() {
    return left_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : left_;
  }

  public static final int RIGHT_FIELD_NUMBER = 6;
  private com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem right_;
  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   * @return Whether the right field is set.
   */
  @java.lang.Override
  public boolean hasRight() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   * @return The right.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getRight() {
    return right_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : right_;
  }
  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getRightOrBuilder() {
    return right_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : right_;
  }

  public static final int THRESHOLD_FIELD_NUMBER = 7;
  private com.grpcdemo.instrument.v1.proto.instrument.Threshold threshold_;
  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   * @return Whether the threshold field is set.
   */
  @java.lang.Override
  public boolean hasThreshold() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   * @return The threshold.
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.Threshold getThreshold() {
    return threshold_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance() : threshold_;
  }
  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   */
  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder getThresholdOrBuilder() {
    return threshold_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance() : threshold_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, uid_);
    }
    if (buyable_ != false) {
      output.writeBool(2, buyable_);
    }
    if (sellable_ != false) {
      output.writeBool(3, sellable_);
    }
    if (status_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.UNSPECIFIED.getNumber()) {
      output.writeEnum(4, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getLeft());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(6, getRight());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(7, getThreshold());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uid_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uid_);
    }
    if (buyable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, buyable_);
    }
    if (sellable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, sellable_);
    }
    if (status_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLeft());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getRight());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getThreshold());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.grpcdemo.instrument.v1.proto.instrument.TradingPair)) {
      return super.equals(obj);
    }
    com.grpcdemo.instrument.v1.proto.instrument.TradingPair other = (com.grpcdemo.instrument.v1.proto.instrument.TradingPair) obj;

    if (!getUid()
        .equals(other.getUid())) return false;
    if (getBuyable()
        != other.getBuyable()) return false;
    if (getSellable()
        != other.getSellable()) return false;
    if (status_ != other.status_) return false;
    if (hasLeft() != other.hasLeft()) return false;
    if (hasLeft()) {
      if (!getLeft()
          .equals(other.getLeft())) return false;
    }
    if (hasRight() != other.hasRight()) return false;
    if (hasRight()) {
      if (!getRight()
          .equals(other.getRight())) return false;
    }
    if (hasThreshold() != other.hasThreshold()) return false;
    if (hasThreshold()) {
      if (!getThreshold()
          .equals(other.getThreshold())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + UID_FIELD_NUMBER;
    hash = (53 * hash) + getUid().hashCode();
    hash = (37 * hash) + BUYABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getBuyable());
    hash = (37 * hash) + SELLABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSellable());
    hash = (37 * hash) + STATUS_FIELD_NUMBER;
    hash = (53 * hash) + status_;
    if (hasLeft()) {
      hash = (37 * hash) + LEFT_FIELD_NUMBER;
      hash = (53 * hash) + getLeft().hashCode();
    }
    if (hasRight()) {
      hash = (37 * hash) + RIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getRight().hashCode();
    }
    if (hasThreshold()) {
      hash = (37 * hash) + THRESHOLD_FIELD_NUMBER;
      hash = (53 * hash) + getThreshold().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.grpcdemo.instrument.v1.proto.instrument.TradingPair prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code instrument.v1.TradingPair}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:instrument.v1.TradingPair)
      com.grpcdemo.instrument.v1.proto.instrument.TradingPairOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPair_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPair_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.grpcdemo.instrument.v1.proto.instrument.TradingPair.class, com.grpcdemo.instrument.v1.proto.instrument.TradingPair.Builder.class);
    }

    // Construct using com.grpcdemo.instrument.v1.proto.instrument.TradingPair.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        getLeftFieldBuilder();
        getRightFieldBuilder();
        getThresholdFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      uid_ = "";
      buyable_ = false;
      sellable_ = false;
      status_ = 0;
      left_ = null;
      if (leftBuilder_ != null) {
        leftBuilder_.dispose();
        leftBuilder_ = null;
      }
      right_ = null;
      if (rightBuilder_ != null) {
        rightBuilder_.dispose();
        rightBuilder_ = null;
      }
      threshold_ = null;
      if (thresholdBuilder_ != null) {
        thresholdBuilder_.dispose();
        thresholdBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPairProto.internal_static_instrument_v1_TradingPair_descriptor;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getDefaultInstanceForType() {
      return com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance();
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair build() {
      com.grpcdemo.instrument.v1.proto.instrument.TradingPair result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPair buildPartial() {
      com.grpcdemo.instrument.v1.proto.instrument.TradingPair result = new com.grpcdemo.instrument.v1.proto.instrument.TradingPair(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.grpcdemo.instrument.v1.proto.instrument.TradingPair result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.uid_ = uid_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.buyable_ = buyable_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.sellable_ = sellable_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.left_ = leftBuilder_ == null
            ? left_
            : leftBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.right_ = rightBuilder_ == null
            ? right_
            : rightBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.threshold_ = thresholdBuilder_ == null
            ? threshold_
            : thresholdBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.grpcdemo.instrument.v1.proto.instrument.TradingPair) {
        return mergeFrom((com.grpcdemo.instrument.v1.proto.instrument.TradingPair)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.grpcdemo.instrument.v1.proto.instrument.TradingPair other) {
      if (other == com.grpcdemo.instrument.v1.proto.instrument.TradingPair.getDefaultInstance()) return this;
      if (!other.getUid().isEmpty()) {
        uid_ = other.uid_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getBuyable() != false) {
        setBuyable(other.getBuyable());
      }
      if (other.getSellable() != false) {
        setSellable(other.getSellable());
      }
      if (other.status_ != 0) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasLeft()) {
        mergeLeft(other.getLeft());
      }
      if (other.hasRight()) {
        mergeRight(other.getRight());
      }
      if (other.hasThreshold()) {
        mergeThreshold(other.getThreshold());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              uid_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              buyable_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              sellable_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  getLeftFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  getRightFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getThresholdFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object uid_ = "";
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The uid.
     */
    public java.lang.String getUid() {
      java.lang.Object ref = uid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return The bytes for uid.
     */
    public com.google.protobuf.ByteString
        getUidBytes() {
      java.lang.Object ref = uid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The uid to set.
     * @return This builder for chaining.
     */
    public Builder setUid(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @return This builder for chaining.
     */
    public Builder clearUid() {
      uid_ = getDefaultInstance().getUid();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string uid = 1 [json_name = "uid"];</code>
     * @param value The bytes for uid to set.
     * @return This builder for chaining.
     */
    public Builder setUidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      uid_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean buyable_ ;
    /**
     * <code>bool buyable = 2 [json_name = "buyable"];</code>
     * @return The buyable.
     */
    @java.lang.Override
    public boolean getBuyable() {
      return buyable_;
    }
    /**
     * <code>bool buyable = 2 [json_name = "buyable"];</code>
     * @param value The buyable to set.
     * @return This builder for chaining.
     */
    public Builder setBuyable(boolean value) {

      buyable_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool buyable = 2 [json_name = "buyable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBuyable() {
      bitField0_ = (bitField0_ & ~0x00000002);
      buyable_ = false;
      onChanged();
      return this;
    }

    private boolean sellable_ ;
    /**
     * <code>bool sellable = 3 [json_name = "sellable"];</code>
     * @return The sellable.
     */
    @java.lang.Override
    public boolean getSellable() {
      return sellable_;
    }
    /**
     * <code>bool sellable = 3 [json_name = "sellable"];</code>
     * @param value The sellable to set.
     * @return This builder for chaining.
     */
    public Builder setSellable(boolean value) {

      sellable_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool sellable = 3 [json_name = "sellable"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSellable() {
      bitField0_ = (bitField0_ & ~0x00000004);
      sellable_ = false;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus getStatus() {
      com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus result = com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.forNumber(status_);
      return result == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus.UNRECOGNIZED : result;
    }
    /**
     * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem left_;
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder> leftBuilder_;
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     * @return Whether the left field is set.
     */
    public boolean hasLeft() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     * @return The left.
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getLeft() {
      if (leftBuilder_ == null) {
        return left_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : left_;
      } else {
        return leftBuilder_.getMessage();
      }
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public Builder setLeft(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem value) {
      if (leftBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        left_ = value;
      } else {
        leftBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public Builder setLeft(
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder builderForValue) {
      if (leftBuilder_ == null) {
        left_ = builderForValue.build();
      } else {
        leftBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public Builder mergeLeft(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem value) {
      if (leftBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          left_ != null &&
          left_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance()) {
          getLeftBuilder().mergeFrom(value);
        } else {
          left_ = value;
        }
      } else {
        leftBuilder_.mergeFrom(value);
      }
      if (left_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public Builder clearLeft() {
      bitField0_ = (bitField0_ & ~0x00000010);
      left_ = null;
      if (leftBuilder_ != null) {
        leftBuilder_.dispose();
        leftBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder getLeftBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return getLeftFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getLeftOrBuilder() {
      if (leftBuilder_ != null) {
        return leftBuilder_.getMessageOrBuilder();
      } else {
        return left_ == null ?
            com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : left_;
      }
    }
    /**
     * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder> 
        getLeftFieldBuilder() {
      if (leftBuilder_ == null) {
        leftBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder>(
                getLeft(),
                getParentForChildren(),
                isClean());
        left_ = null;
      }
      return leftBuilder_;
    }

    private com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem right_;
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder> rightBuilder_;
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     * @return Whether the right field is set.
     */
    public boolean hasRight() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     * @return The right.
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getRight() {
      if (rightBuilder_ == null) {
        return right_ == null ? com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : right_;
      } else {
        return rightBuilder_.getMessage();
      }
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public Builder setRight(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem value) {
      if (rightBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        right_ = value;
      } else {
        rightBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public Builder setRight(
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder builderForValue) {
      if (rightBuilder_ == null) {
        right_ = builderForValue.build();
      } else {
        rightBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public Builder mergeRight(com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem value) {
      if (rightBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          right_ != null &&
          right_ != com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance()) {
          getRightBuilder().mergeFrom(value);
        } else {
          right_ = value;
        }
      } else {
        rightBuilder_.mergeFrom(value);
      }
      if (right_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public Builder clearRight() {
      bitField0_ = (bitField0_ & ~0x00000020);
      right_ = null;
      if (rightBuilder_ != null) {
        rightBuilder_.dispose();
        rightBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder getRightBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return getRightFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getRightOrBuilder() {
      if (rightBuilder_ != null) {
        return rightBuilder_.getMessageOrBuilder();
      } else {
        return right_ == null ?
            com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.getDefaultInstance() : right_;
      }
    }
    /**
     * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder> 
        getRightFieldBuilder() {
      if (rightBuilder_ == null) {
        rightBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem.Builder, com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder>(
                getRight(),
                getParentForChildren(),
                isClean());
        right_ = null;
      }
      return rightBuilder_;
    }

    private com.grpcdemo.instrument.v1.proto.instrument.Threshold threshold_;
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.Threshold, com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder, com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder> thresholdBuilder_;
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     * @return Whether the threshold field is set.
     */
    public boolean hasThreshold() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     * @return The threshold.
     */
    public com.grpcdemo.instrument.v1.proto.instrument.Threshold getThreshold() {
      if (thresholdBuilder_ == null) {
        return threshold_ == null ? com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance() : threshold_;
      } else {
        return thresholdBuilder_.getMessage();
      }
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public Builder setThreshold(com.grpcdemo.instrument.v1.proto.instrument.Threshold value) {
      if (thresholdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        threshold_ = value;
      } else {
        thresholdBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public Builder setThreshold(
        com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder builderForValue) {
      if (thresholdBuilder_ == null) {
        threshold_ = builderForValue.build();
      } else {
        thresholdBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public Builder mergeThreshold(com.grpcdemo.instrument.v1.proto.instrument.Threshold value) {
      if (thresholdBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          threshold_ != null &&
          threshold_ != com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance()) {
          getThresholdBuilder().mergeFrom(value);
        } else {
          threshold_ = value;
        }
      } else {
        thresholdBuilder_.mergeFrom(value);
      }
      if (threshold_ != null) {
        bitField0_ |= 0x00000040;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public Builder clearThreshold() {
      bitField0_ = (bitField0_ & ~0x00000040);
      threshold_ = null;
      if (thresholdBuilder_ != null) {
        thresholdBuilder_.dispose();
        thresholdBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder getThresholdBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getThresholdFieldBuilder().getBuilder();
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    public com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder getThresholdOrBuilder() {
      if (thresholdBuilder_ != null) {
        return thresholdBuilder_.getMessageOrBuilder();
      } else {
        return threshold_ == null ?
            com.grpcdemo.instrument.v1.proto.instrument.Threshold.getDefaultInstance() : threshold_;
      }
    }
    /**
     * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.grpcdemo.instrument.v1.proto.instrument.Threshold, com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder, com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder> 
        getThresholdFieldBuilder() {
      if (thresholdBuilder_ == null) {
        thresholdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.grpcdemo.instrument.v1.proto.instrument.Threshold, com.grpcdemo.instrument.v1.proto.instrument.Threshold.Builder, com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder>(
                getThreshold(),
                getParentForChildren(),
                isClean());
        threshold_ = null;
      }
      return thresholdBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:instrument.v1.TradingPair)
  }

  // @@protoc_insertion_point(class_scope:instrument.v1.TradingPair)
  private static final com.grpcdemo.instrument.v1.proto.instrument.TradingPair DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.grpcdemo.instrument.v1.proto.instrument.TradingPair();
  }

  public static com.grpcdemo.instrument.v1.proto.instrument.TradingPair getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TradingPair>
      PARSER = new com.google.protobuf.AbstractParser<TradingPair>() {
    @java.lang.Override
    public TradingPair parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<TradingPair> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TradingPair> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.grpcdemo.instrument.v1.proto.instrument.TradingPair getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

