// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/trading_pair.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public interface TradingPairOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instrument.v1.TradingPair)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>bool buyable = 2 [json_name = "buyable"];</code>
   * @return The buyable.
   */
  boolean getBuyable();

  /**
   * <code>bool sellable = 3 [json_name = "sellable"];</code>
   * @return The sellable.
   */
  boolean getSellable();

  /**
   * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.instrument.v1.TradingPairStatus status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairStatus getStatus();

  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   * @return Whether the left field is set.
   */
  boolean hasLeft();
  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   * @return The left.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getLeft();
  /**
   * <code>.instrument.v1.TradingPairItem left = 5 [json_name = "left"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getLeftOrBuilder();

  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   * @return Whether the right field is set.
   */
  boolean hasRight();
  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   * @return The right.
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairItem getRight();
  /**
   * <code>.instrument.v1.TradingPairItem right = 6 [json_name = "right"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.TradingPairItemOrBuilder getRightOrBuilder();

  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   * @return Whether the threshold field is set.
   */
  boolean hasThreshold();
  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   * @return The threshold.
   */
  com.grpcdemo.instrument.v1.proto.instrument.Threshold getThreshold();
  /**
   * <code>.instrument.v1.Threshold threshold = 7 [json_name = "threshold"];</code>
   */
  com.grpcdemo.instrument.v1.proto.instrument.ThresholdOrBuilder getThresholdOrBuilder();
}
