// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: instrument/v1/trading_pair.proto
// Protobuf Java Version: 4.28.0

package com.grpcdemo.instrument.v1.proto.instrument;

public interface TradingPairItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:instrument.v1.TradingPairItem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The uid.
   */
  java.lang.String getUid();
  /**
   * <code>string uid = 1 [json_name = "uid"];</code>
   * @return The bytes for uid.
   */
  com.google.protobuf.ByteString
      getUidBytes();

  /**
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2 [json_name = "symbol"];</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
   * @return The decimalPlaces.
   */
  java.lang.String getDecimalPlaces();
  /**
   * <code>string decimal_places = 3 [json_name = "decimalPlaces"];</code>
   * @return The bytes for decimalPlaces.
   */
  com.google.protobuf.ByteString
      getDecimalPlacesBytes();
}
