apiVersion: v1
kind: Service
metadata:
  name: grpcdemo-java-server-service
spec:
  selector:
    app: grpcdemo-java-server
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 2222
  type: LoadBalancer