apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcdemo-go-server-deployment
  labels:
    app: grpcdemo-go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpcdemo-go-server
  template:
    metadata:
      labels:
        app: grpcdemo-go-server
    spec:
      containers:
        - name: grpcdemo-go-server
          image: grpcdemo-go-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2222
              name: tcp
          resources:
            limits:
              memory: "128Mi"
              cpu: "20m"
            requests:
              memory: "64Mi"
              cpu: "10m"

