FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o grpcdemo-go-client cmd/client/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/grpcdemo-go-client client

EXPOSE 2223

CMD ["./client"]