FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o grpcdemo-go-server cmd/server/main.go

FROM alpine:latest

WORKDIR /root/

COPY --from=builder /app/grpcdemo-go-server server

EXPOSE 2222

CMD ["./server"]